//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach_Alpinizm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlpinizmEntities : DbContext
    {
        private static AlpinizmEntities _context;
        public AlpinizmEntities()
            : base("name=AlpinizmEntities1")
        {
        }

        public static AlpinizmEntities GetContext()
        {
            if (_context == null)
                _context = new AlpinizmEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alpinists> alpinists { get; set; }
        public virtual DbSet<category_of_difficulty> category_of_difficulty { get; set; }
        public virtual DbSet<climbers_in_groups> climbers_in_groups { get; set; }
        public virtual DbSet<equipment> equipment { get; set; }
        public virtual DbSet<equipment_inventory> equipment_inventory { get; set; }
        public virtual DbSet<groups> groups { get; set; }
        public virtual DbSet<mountain> mountain { get; set; }
        public virtual DbSet<mountain_climbs> mountain_climbs { get; set; }
        public virtual DbSet<position> position { get; set; }
        public virtual DbSet<sport_category> sport_category { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<team> team { get; set; }
        public virtual DbSet<team_leaders> team_leaders { get; set; }
    }
}
