//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach_Alpinizm
{
    using System;
    using System.Collections.Generic;
    
    public partial class alpinists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public alpinists()
        {
            this.climbers_in_groups = new HashSet<climbers_in_groups>();
        }
    
        public int ID_alpinist { get; set; }
        public string Surname { get; set; }
        public string Name_ { get; set; }
        public string Address_ { get; set; }
        public string Phone { get; set; }
        public string Sex { get; set; }
        public Nullable<int> ID_sport_category { get; set; }
    
        public virtual sport_category sport_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<climbers_in_groups> climbers_in_groups { get; set; }
    }
}
