//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach_Alpinizm
{
    using System;
    using System.Collections.Generic;
    
    public partial class team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public team()
        {
            this.team_leaders = new HashSet<team_leaders>();
        }
    
        public int ID_team_member { get; set; }
        public string Surname_name { get; set; }
        public Nullable<System.DateTime> Date_of_birth { get; set; }
        public string Address_ { get; set; }
        public Nullable<int> ID_position { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Password_ { get; set; }
        public string Login_ { get; set; }
    
        public virtual position position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<team_leaders> team_leaders { get; set; }
    }
}
